# Generated by Django 5.2.17 on 2026-10-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('partner_sku', models.CharField(max_length=100, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('unit_code', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=100)),
                ('serial_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_expiry_date', models.BooleanField(default=False)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('product_units', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
