# Generated by Django 5.2.17 on 2026-10-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Product',
        ),
    ]
