# Generated by Django 5.2.17 on 2026-10-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_inventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_type',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
