# Generated by Django 5.2.17 on 2026-10-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_product_serial_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at', 'id'], name='product_update_at_id_idx'),
        ),
    ]
