# Generated by Django 5.2.17 on 2026-10-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedata',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
