# Generated by Django 5.2.17 on 2026-10-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_changedata_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changedata',
            name='received_via',
        ),
    ]
